import type { Node, Metrics } from "../src/lib/api.ts";

const GB = 1024 ** 3;
const metrics: Metrics = {
  uptime: 42 * 86400,
  cpu: 12.8,
  load: [0.19, 0.28, 0.21],
  mem_total: 4 * GB,
  mem_used: 1.5 * GB,
  swap_total: 2 * GB,
  swap_used: 0,
  disk_total: 80 * GB,
  disk_used: 19 * GB,
  net_rx: 2.4 * 1024 ** 2,
  net_tx: 1.1 * 1024 ** 2,
  total_rx: 318 * GB,
  total_tx: 126 * GB,
  month_rx: 128 * GB,
  month_tx: 52 * GB,
  tcp: 42,
  udp: 12,
  procs: 86,
};
const base: Node = {
  id: 1,
  name: "香港 · 直连专线",
  sort: 0,
  public: true,
  online: true,
  country: "HK",
  group: "亚洲线路",
  last_seen: Math.floor(Date.now() / 1000),
  last_seen_ago: 1,
  metrics,
  os: "Debian GNU/Linux 13",
  kernel: "6.12",
  arch: "x86_64",
  virt: "KVM",
  cpu_name: "AMD EPYC 7B13",
  cpu_cores: 2,
  mem_total: 4 * GB,
  swap_total: 2 * GB,
  disk_total: 80 * GB,
  agent_version: "1.4.0",
  price: 29,
  currency: "CNY",
  billing_cycle: "monthly",
  expires_at: "2026-12-08",
  expires_in: 59,
  traffic_limit: 1000 * GB,
  traffic_mode: "sum",
  traffic_reset_day: 1,
  total_rx: 318 * GB,
  total_tx: 126 * GB,
  month_rx: 128 * GB,
  month_tx: 52 * GB,
  month_used: 180 * GB,
  month_start: "2026-10-01",
  day_rx: 12 * GB,
  day_tx: 5 * GB,
  public_remark: "低延迟直连 · 轻松看清每一份负载",
};
export const demoNodes: Node[] = [
  base,
  {
    ...base,
    id: 2,
    sort: 1,
    name: "东京 · 樱花快车",
    country: "JP",
    price: 680,
    currency: "JPY",
    expires_in: 6,
    cpu_cores: 4,
    public_remark: "独立大内存 · 本月流量正在上报",
    metrics: { ...metrics, cpu: 38.6, mem_used: 2.8 * GB },
  },
  {
    ...base,
    id: 3,
    sort: 2,
    name: "洛杉矶 · 西海岸",
    country: "US",
    group: "美洲线路",
    price: 5,
    currency: "USD",
    expires_in: null,
    expires_at: null,
    public_remark: "跨洋线路 · 没有设置到期日期",
    metrics: { ...metrics, cpu: 4.2, net_tx: 3.8 * 1024 ** 2 },
  },
  {
    ...base,
    id: 4,
    sort: 3,
    name: "新加坡 · 狮城加速",
    country: "SG",
    price: 8,
    currency: "USD",
    expires_in: 17,
    public_remark: "热门节点 · 当前负载如实展示",
    metrics: { ...metrics, cpu: 86.4, mem_used: 3.6 * GB },
  },
  {
    ...base,
    id: 5,
    sort: 4,
    name: "法兰克福 · 欧洲站",
    country: "DE",
    group: "欧洲线路",
    price: 4,
    currency: "EUR",
    online: false,
    metrics: null,
    last_seen_ago: 3600,
    expires_in: -2,
    public_remark: "节点离线 · 等待重新连接",
  },
  {
    ...base,
    id: 6,
    sort: 5,
    name: "首尔 · 新店开张",
    country: "KR",
    group: "",
    metrics: null,
    last_seen_ago: null,
    cpu_cores: 0,
    mem_total: 0,
    disk_total: 0,
    price: 0,
    expires_in: null,
    public_remark: "已连接 · 等待首次指标上报",
  },
];

export function demoHistory() {
  const start = Math.floor(Date.now() / 60000) * 60 - 60 * 90;
  return {
    step: 60,
    probes: { "1": "香港线路", "2": "东京线路" },
    loss: { "2": 2 },
    metrics: Array.from({ length: 90 }, (_, index) => ({
      ts: start + index * 60,
      minutes: 1,
      cpu: 13 + Math.sin(index / 7) * 9,
      cpu_max: 30,
      mem_used: 1.5 * GB,
      disk_used: 19 * GB,
      net_rx: (2 + Math.sin(index / 5)) * 1024 ** 2,
      net_tx: (1 + Math.cos(index / 6) * 0.6) * 1024 ** 2,
      net_rx_max: 4 * 1024 ** 2,
      net_tx_max: 2 * 1024 ** 2,
    })),
    ping: [1, 2].flatMap((id) =>
      Array.from({ length: 90 }, (_, index) => ({
        task_id: id,
        ts: start + index * 60,
        latency: (id === 1 ? 19 : 48) + Math.sin(index / 8) * 3,
        band: [id === 1 ? 17 : 45, id === 1 ? 23 : 55],
      })),
    ),
  };
}
